services:
  db:
    container_name: patient-management-db
    image: postgres:14.1-alpine
    restart: always
    hostname: localhost
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: patient_management_db
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local